name: "Deploy Codigo Facilito"

on: 
  push:
    branches: ["main"]


jobs:
  deploy-codigoFacilito:
    runs-on: ubuntu-latest

    env:
      Name: Codigofacilito

    steps: 
      - run: echo "Hacemos pull del codigo"
      - name: working dir
        run: ls -al

      - name: Action
        uses: actions/checkout@v4

      - name: working dir after actions
        run: ls -al